# Basic python problems

1) Have the function QuestionsMarks(str) take the str string parameter, which will contain single digit numbers, letters, and question marks, and check if there are exactly 3 question marks between every pair of two numbers that add up to 10. If so, then your program should return the string true, otherwise it should return the string false. If there aren't any two numbers that add up to 10 in the string, then your program should return false as well.

For example: if str is "arrb6???4xxbl5???eee5" then your program should return true because there are exactly 3 question marks between 6 and 4, and 3 question marks between 5 and 5 at the end of the string.

Input: "aa6?9" Output: false

Input: "acc?7??sss?3rr1??????5" Output: true

In [93]:
def question_mark(s):
    l=[]
    l1=[]
    count=0
    count_10=0
    
    for i in s:
        if i.isdigit() or i=='?':
            l.append(i)
    
    for i in range(len(l)):
        if l[i].isdigit():
            if i+4<len(l) and l[i+4].isdigit():
                count+=1
    
    for i in l:
        if i.isdigit():
            l1.append(int(i))
    for i in range(len(l1)):
        if i+1<len(l1) and l1[i]+l1[i+1]==10:
            count_10+=1
            
    if count>=1 and count_10>=1:
        return True
    else:
        return False
    
s="aa6?9"
print(question_mark(s))

False


2) Find Intersection
Have the function FindIntersection(strArr) read the array of strings stored in strArr which will contain 2 elements: the first element will represent a list of comma-separated numbers sorted in ascending order, the second element will represent a second list of comma-separated numbers (also sorted). Your goal is to return a comma-separated string containing the numbers that occur in elements of strArr in sorted order. If there is no intersection, return the string false.

Examples

Input: ["1, 3, 4, 7, 13", "1, 2, 4, 13, 15"]

Output: 1,4,13

Input: ["1, 3, 9, 10, 17, 18", "1, 4, 9, 10"]

Output: 1,9,10

In [111]:
a=["1, 3, 4, 7, 13", "1, 2, 4, 13, 15"]
a1=a[0].split()
a2=a[1].split()
a11=[]
a12=[]
a13=[]

for i in a1:
    a11.append(i.replace(',',''))
    
for i in a2:
    a12.append(i.replace(',',''))
    
for i in a11:
    if i in a12:
        a13.append(i)
a13


['1', '4', '13']

3)First Reverse
Have the function FirstReverse(str) take the str parameter being passed and return the string in reversed order. For example: if the input string is "Hello World and Coders" then your program should return the string sredoC dna dlroW olleH.
Examples

Input: "coderbyte"

Output: etybredoc

Input: "I Love Code"

Output: edoC evoL I

In [114]:
b='coderbyte'
res=b[::-1]
res

'etybredoc'

4) First Factorial
Have the function FirstFactorial(num) take the num parameter being passed and return the factorial of it. For example: if num = 4, then your program should return (4 * 3 * 2 * 1) = 24. For the test cases, the range will be between 1 and 18 and the input will always be an integer.
Examples

Input: 4

Output: 24

Input: 8

Output: 40320

In [126]:
n=int(input('enter the number: '))
z=[]
result=1
for i in range(1,n+1):
    z.append(i)
for i in z:
    result*=i
print(result)    

enter the number: 8
40320


5)Have the function LongestWord(sen) take the sen parameter being passed and return the longest word in the string. If there are two or more words that are the same length, return the first word from the string with that length. Ignore punctuation and assume sen will not be empty. Words may also contain numbers, for example "Hello world123 567"
Examples

Input: "fun&!! time"
    
Output: time
    
Input: "I love dogs"
    
Output: love

In [205]:
def LongestWord(sen):
    x=sen.split()
    y1=[]
    count1=''
    
    for i in range(len(x)):
        if x[i].isalpha():
            y1.append(x[i])
        else:
            for j in x[i]:
                if j.isalpha():
                    count1+=j
    y1.append(count1)
    
    long_word=''
    for i in y1:
        if len(i)>len(long_word):
            long_word=i
    return long_word
        
            
sen="Hello world123567"
print(LongestWord(sen))

Hello


6)CodelandUsernameValidation(str) take the str parameter being passed and determine if the string is a valid username according to the following rules:

1. The username is between 4 and 25 characters.
2. It must start with a letter.
3. It can only contain letters, numbers, and the underscore character.
4. It cannot end with an underscore character.

If the username is valid then your program should return the string true, otherwise return the string false.
Examples

Input: "aa_"

Output: false

Input: "u__hello_world123"

Output: true

In [220]:
def CodelandUsernameValidation(t):
    if len(t)>=4 and len(t)<=25:
        if t[-1]!='_' and t[0].isalpha():
            for i in t:
                if i.isalnum() or i=='_!"£$%6=?':
                    return True
                else:
                    return False
        else:
            return False
    else:
        return False
    

                    
t= "a1__!£$123_a"                    
print(CodelandUsernameValidation(t))

True


7) #Li1
#WAP to remove empty strings from the list of strings. Take list as input from the user.

#For example: Input: ["My", "name", "", "is", "", "Alankrita", "", "."]
     #       Output: ["My", "name", "is", "Alankrita", "."]

In [221]:
c= ["My", "name", "", "is", "", "Alankrita", "", "."] 
c1=[]
for i in c:
    if i not in c1 and i!="":
        c1.append(i)
c1

['My', 'name', 'is', 'Alankrita', '.']

8) #Li2
#WAP to make a list of all the characters starting from character 'A' to the input character from the user.

#For e.g. Input: 'H'
 #Output: ["A", "B", "C", "D", "E", "F", "G", "H"]

In [238]:

d1=[]
for s in range(ord('A'),ord('I')):
    d1.append(chr(s))
d1


['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

9)Li4
#Write a python program to find the maximum and minimum number in a list of 10 elements 
#(taken as input from the user) and also find the index position of the these numbers.
    
  #For example: Input : [25, 2, 1, 86, 42, 32, 27, 12, 31, 10]
#Output: Max Number: 86, Index of Max Number: 3
#Min Number: 1, Index of Min Number: 2

In [240]:
e=[25, 2, 1, 86, 42, 32, 27, 12, 31, 10] 
print(max(e))
e1=min(e)
print(min(e))
print(e.index(e1))

86
1
2


10)#Li5
#Given two Python lists of same length. Iterate both lists simultaneously such that list1 
  #should display item in original order and list2 in reverse order.
    
  #For example: Input = list1 = [10, 20, 30, 40]
#list2 = [100, 200, 300, 400]
 #Output: 10 400
 #20 300
 #30 200

In [248]:
f1=[10, 20, 30, 40] 
f2=[100, 200, 300, 400]

for i in range(len(f1)):
    print(f1[1],f2[i])

    
    

20 100
20 200
20 300
20 400


11)#Li6
#WAP to concatenate two lists index-wise.
#list1 = ["M", "na", "i", "Ashu"]
#list2 = ["y", "me", "s", "tosh"]
#Output: ['My', 'name', 'is', 'Ashutosh']


In [1]:
g1= ["M", "na", "i", "Ashu"]
g2=["y", "me", "s", "tosh"]
g3=[]

for i in range(len(g1)):
    g3.append(g1[i]+g2[i])
g3
    

['My', 'name', 'is', 'Ashutosh']

12)#S2
#Write a Python program to find the digits which are absent in a given mobile number.

  #For example: Input : 9354328855
    #Output: 0167

In [17]:
h1='9354328855'
h2=[]
h3=[]
h4=[]
h5=[]
for i in range(len(h1)):
    for j in h1[i]:
        h2.append(j)
for i in h2:
    h3.append(int(i))
for i in range(0,10):
    h4.append(i)
for i in h4:
    if i not in h3:
        h5.append(i)
h5

[0, 1, 6, 7]

13)#S4
#WAP in python that accepts a hyphen-separated sequence of 
#alphabets as input and prints the words in a hyphen-separated 
#sequence after sorting them alphabetically.

#For e.g. Input: "p-y-t-h-o-n"
 #Output: ['h', 'n','o', 'p', 't', 'y']

In [21]:
s1= "p-y-t-h-o-n"
s2=s1.split('-')
s2.sort()
s2

['h', 'n', 'o', 'p', 't', 'y']

14)#S5
#WAP in python to find the number of vowels, consonants, digits, special 
#characters and white space characters in a string input by the user.

#Example: Input: "Qwerty@123"
#output: v = 1, c = 5, d = 3, w = 0, s = 1

In [29]:
i1="Qwerty@123"
vowels=0
conso=0
digits=0
special=0

i2=['a','e','i','o','u']
i3='@8&^%$?><./,+-='
i4=[]
for i in range(len(i3)):
    for j in i3[i]:
        i4.append(j)
        
        


for i in i1:
    if i.isdigit():
        digits+=1
    elif i.lower() in i2:
        vowels+=1
    elif i in i4:
        special+=1
    else:
        conso+=1

print(vowels)
print(conso)
print(digits)
print(special)

1
5
3
1


15)
#Li10 Given two lists having names of students and their corrsponding marks. names = ["Ashutosh", "Ajay", "Alankrita", "Rachit", "Komal", "Anil"] marks = [23, 21, 26, 23, 27, 24] Take name of a student as input from the user and output his/her marks.

For e.g.: Input1: "Alankrita" Output1: 26

Input2: "Someone"
Output2: "Student not found"

#Li11
#Extended question of #Li10
#Add an option to change marks of any students in the same code of #Li10. Take student name and new marks from the user. 
#Print the modified list as output.

#For e.g.: Input: "Ajay"
       ## new_mark: 25
       # Output: marks = [23, 25, 26, 23, 27, 24]

In [60]:
names=["Ashutosh", "Ajay", "Alankrita", "Rachit", "Komal", "Anil"]
marks=[23, 21, 26, 23, 27, 24]
res=dict(zip(names,marks))

input_y_n=input('enter y to change student marks or n to display marks: ')

if input_y_n.lower()=='y':
    input1=input('enter the name to change the marks: ')
    for k,v in res.items():
        if k.lower()==input1:
            updated_marks=int(input('enter the new marks: '))
            res[k]=updated_marks
    print(res)
    
    
    
elif input_y_n.lower()=='n':
    m=''
    input2=input('enter the name: ')
    for k,v in res.items():
        if k.lower()==input2:
            m=v
    
    if m in marks:
        print(m)
    else: 
        print('name not found')

enter y to change student marks or n to display marks: y
enter the name to change the marks: ajay
enter the new marks: 90
{'Ashutosh': 23, 'Ajay': 90, 'Alankrita': 26, 'Rachit': 23, 'Komal': 27, 'Anil': 24}


16)#D1
#WAP in Python to merge following dictionaries to create a new one:
#dic1={1:10, 2:20}
#dic2={3:30, 4:40}
#dic3={5:50, 6:60}

In [63]:
j1={1:10, 2:20}
j2={3:30, 4:40}
j3={5:50, 6:60}

j1.update(j2)
j1.update(j3)
j1

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}

17)#Write a Python program to convert all the cases from lower to uppercase and upper to lowercase 
  #and eliminate duplicate letters from a given sequence. 
#i/p: ['a', 'b', 'E', 'f', 'a', 'i', 'o', 'U', 'a']
#o/p: ['A', 'B', 'e', 'F', 'I', 'O', 'u']

In [65]:
k=['a', 'b', 'E', 'f', 'a', 'i', 'o', 'U', 'a']
k1=[]
for i in k:
    if i.islower():
        k1.append(i.upper())
    elif i.isupper():
        k1.append(i.lower())
k1

['A', 'B', 'e', 'F', 'A', 'I', 'O', 'u', 'A']

18)# For a given list of values in descending order, write a method in python to search 
#for a value with the help of Binary Search method. 
#The method should return position of the value and should return -1 if the value not present in the list.

In [37]:
def acending(l):
    for i in range(len(l)):
        for j in range(i,len(l)):
            if l[i]>l[j]:
                l[i],l[j]=l[j],l[i]
                
def char_pos(n):
    for i in l:
        if i==n:
            return l.index(i)
    return '-1'
        
        
        
            
l=[10,29,29,27,80,78] 
acending(l)
n=int(input('enter the number: '))
print(l)
print(char_pos(n))


enter the number: 90
[10, 27, 29, 29, 78, 80]
-1


19)# Write a function in python to find the sum of the cube of elements in a list. 
#The list is received as an argument to the function, in turn, the function must return the sum. 
#Write the main function which invokes the above function.

In [94]:

def cube(m):
    m1=[]
    for i in m:
        i=i**3
        m1.append(i)
    return sum(m1)


m=[2,4,6,8,10]
print(cube(m))



1800


20)#Initialize a dictionary "emp_info" with below details
#In - emp_info['Tom']
#Out - {'email':'tom_latham019@gmail.com', 'Phone': +1987654321, 'City': 'California'}

#In - emp_info['Kathy']
#Out - {'email':'kathy_abram897@gmail.com', 'Phone': +1887654321, 'City': 'New York'}

In [97]:
d={'Tom':{'emaim1l':'tom_latham019@gmail.com', 'Phone': +1987654321, 'City': 'California'},
  'Cathy':{'email':'kathy_abram897@gmail.com', 'Phone': +1887654321, 'City': 'New York'}}
d['Tom']


{'email': 'tom_latham019@gmail.com', 'Phone': 1987654321, 'City': 'California'}

21)##Have the function ABCheck(str) take the str parameter being passed and return the string true if the 
##characters a and b are separated by exactly 3 places anywhere in the string at least once 
##(ie. "lane borrowed" would result in true because there is exactly three characters between a and b).
##Otherwise return the string false.

In [12]:
m1="lane borrowed"

if m1.index('a')-m1.index('b')==4 or m1.index('b')-m1.index('a')==4:
    print('true')
else:
    print('false')
        

true


22)#Create a dictionary out of below inputs
#lst1 = ['emp1', 'emp2', 'emp3']
#emp_key = ['e_name', 'e_id', 'e_sal']
#emp1_val = ['John', 'SG101', '$10,000']
#emp2_val = ['Smith', 'SG102', '$9,000']
#emp3_val = ['Peter', 'SG103', '$9,500']

#Expected Output:- {'emp1':{'e_name':'John', 'e_id':'SG101', 'e_sal':$10,000}, 
#'emp2':{'e_name':'Smith', 'e_id':'SG102', 'e_sal':$9,000}, 

In [19]:
lst1 = ['emp1', 'emp2', 'emp3']
emp_key = ['e_name', 'e_id', 'e_sal']
emp1_val = ['John', 'SG101', '$10,000']
emp2_val = ['Smith', 'SG102', '$9,000']
emp3_val = ['Peter', 'SG103', '$9,500']
m1=[emp1_val,emp2_val,emp3_val]


res1=[dict(zip(emp_key,i)) for i in m1]
res2=dict(zip(lst1,res1))
res2

{'emp1': {'e_name': 'John', 'e_id': 'SG101', 'e_sal': '$10,000'},
 'emp2': {'e_name': 'Smith', 'e_id': 'SG102', 'e_sal': '$9,000'},
 'emp3': {'e_name': 'Peter', 'e_id': 'SG103', 'e_sal': '$9,500'}}

23)#2. Write a Python script to add a key to a dictionary.

#Sample Dictionary : {0: 10, 1: 20}
#Expected Result : {0: 10, 1: 20, 2: 30}

In [22]:
d11={0: 10, 1: 20}
d11[2]=30
d11
d11[2].

{0: 10, 1: 20, 2: 30}

24)#get this pattern
#1
#1 2
#1 2 3
#1 2 3 4




In [53]:
n1=int(input('enter the number: '))
for i in range(1,n1+1):
    for j in range(1,i+1):
        print(j, end='')
    print()
 

enter the number: 3
1
12
123


25)#randomey arrange numbers from 1 to 10

In [64]:
import random
num=list(range(1,11))
random.shuffle(num)

print(num)


[8, 10, 5, 7, 9, 3, 6, 4, 1, 2]


# Numpy

In [65]:
#Write a Numpy program to get the Numpy version and show the Numpy build configuration.
import numpy as np

print(np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/saura/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/saura/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/saura/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/saura/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/saura/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/saura/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/saura/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/saura/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy install:
   

In [70]:
#Write a NumPy program to get help with the add function.
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [75]:
#Write a NumPy program to test whether none of the elements of a given array are zero. 
o1=np.arange(1,5)
print(np.all(o1))

o2=np.arange(0,4)
print(np.all(o2))

#returns true if there is no zeros, returns false if there is a zreo


True
False


In [77]:
#Write a NumPy program to test if any of the elements of a given array are non-zero.
o3=np.array([1,0,0,0])
print(np.any(o3))

o4=np.array([0,0,0,0])
print(np.any(o4))

#returns true if there is aleast 1 non zero element else false all the elements are zero


True
False


In [79]:
#Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).

o5=np.array([1,2,np.nan])

print(np.isfinite(o5))


[ True  True False]


In [84]:
# finding out the shape of an array
arr = [[1,2,3,4],[4,5,6,7]]
ar=np.array(arr)
np.shape(ar)

(2, 4)

In [86]:
#reverse in numpy
ar1=np.arange(0,12,2)
ar1[::-1]

array([10,  8,  6,  4,  2,  0])

In [91]:
#How do you count the frequency of a given positive value appearing in the NumPy array?
ar2=np.array([1,2,0,0,0,0,3,3,3,1,2,8])

result=np.bincount(ar2)
print(result)

[4 2 2 3 0 0 0 0 1]


In [105]:
#How do we check for an empty array (or zero elements array)?
ar3=np.zeros((1,0))
ar3.size

0

In [116]:
#How is arr[:,0] different from arr[:,[0]]
ar4 = np.array([[1,2,3,4],[5,6,7,8]])
print(ar4[:,0])
print('\n',ar4[:,[0]])

[1 5]

 [[1]
 [5]]


In [121]:
# multiplying 2 elements in array

arr1=np.arange(10,19).reshape(3,3)
arr2=np.arange(0,9).reshape(3,3)

print('1st array: ', arr1)
print('2nd array: ', arr2)

res1=arr1.dot(arr2)
res1

1st array:  [[10 11 12]
 [13 14 15]
 [16 17 18]]
2nd array:  [[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[105, 138, 171],
       [132, 174, 216],
       [159, 210, 261]])

In [12]:
import numpy as np
arr3=np.array([[1,2],[3,4]])
arr4=np.array([[5,6]])

c=np.concatenate((arr3,arr4),axis=0)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
import numpy as np
arr3=np.array([[1,2],[3,4]])
arr4=np.array([[5,6]])

c=np.concatenate((arr3,arr4.T),axis=1)
c

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
arr = np.array(['i', 'love', 'NumPy', 'AND', 'interviewbit'], dtype=str)

upper=

In [1]:
myTuple = ("John", "Peter", "Vicky")

x = "#".join(myTuple)

print(x)

John#Peter#Vicky


In [4]:
txt = "Thank you for the music\nWelcome to the jungle"

x = txt.splitlines()

print(x)

['Thank you for the music', 'Welcome to the jungle']


In [2]:
a=[3,4,5]
for i in a:
    print(i)

3
4
5


In [3]:
x=3
y=1
while(y!=x):
    print(y)
    y=y+1

1
2


In [5]:
a=1

def add(b):
    return a+b

c=add(10)
c

11

In [15]:
def f(*x):
    return sum(x)

c=f(*6)
c

TypeError: __main__.f() argument after * must be an iterable, not int

In [23]:
class Calculator:
    def add(self,a,b):
        return a+b
    def sub(self,a,b):
        return a-b
    def mul(selfa,b):
        return a*b
    def div(self,a,b):
        return a/b
    
# Create an instance of the Calculator class
calc = Calculator()

# Call the add method with two arguments
result = calc.add(5, 3)

# Print the result
print(result)  # Output: 8


8


In [24]:
class Circle(object):
    
    # Constructor
    def __init__(self, radius=3, color='blue'):
        self.radius = radius
        self.color = color 
    
    # Method
    def add_radius(self, r):
        self.radius = self.radius + r
        return(self.radius)
    
    # Method
    def drawCircle(self):
        plt.gca().add_patch(plt.Circle((0, 0), radius=self.radius, fc=self.color))
        plt.axis('scaled')
        plt.show()  

In [26]:
x=1

if(x!=1):

    print('Hello')

else:

    print('Hi')

print('Mike')

Hi
Mike


In [27]:
A = ['1','2','3']

for a in A:

    print(2*a)

11
22
33


In [30]:
def Delta(x):

    if x==0:

        y=1

    else:

        y=0

    return(y)
print(Delta(0))

1


In [39]:
l=[1,2]
a=set(l)
b={1,3}
a.intersection(b)

{1}

In [41]:

b.difference(a)

{3}

In [42]:
x = {"a", "b", "c"}
y = {"f", "e", "d", "c", "b", "a"}

z = x.issubset(y)

print(z)

True


In [43]:
x = {"f", "e", "d", "c", "b", "a"}
y = {"a", "b", "c"}

z = x.issuperset(y)

print(z)

True


In [48]:
points = [1, 4, 2, 9, 7, 8, 9, 3, 1]

x = points.count(0)
x

0

In [51]:
points.index(9)

3

In [57]:
file=open('LM10.txt','r')


In [58]:
file.name

'LM10.txt'

In [59]:
file.mode

'r'

In [61]:
file_content=file.read()
print(file_content)

In [62]:
file.close()

In [63]:
with open('LM10.txt','r') as file1:
    filecontent=file1.read()
    print(filecontent)

In [78]:
file=open('LM10.txt','a')
file.write('hi my name is saurabh.')
file.close()

In [80]:
file=open('LM10.txt','r')
for i in file:
    print(i)
file.close()

hi my name is saurabhhi my name is saurabh.hi my name is saurabh.


In [81]:
with open('LM10.txt','r') as file1:
    filecontent=file1.read()
    print(filecontent)

hi my name is saurabhhi my name is saurabh.hi my name is saurabh.


In [86]:
file=open('LM10.txt', 'w')
file.write('hello')
file.close()

In [88]:
file=open('LM10.txt', 'r')
file.read()
file.close()

In [89]:
words_to_replace=['hello']

with open('LM10.txt','r') as file:
    content=file.read()

for i in words_to_replace:
    content=content.replace(i,'hi')
    
with open('LM10.txt','w') as file:
    file.write(content)

In [90]:
file=open('LM10.txt','r')
file.read()

'hi'

In [98]:
import pandas as banana

df=banana.DataFrame({'a':[11,25,31],'b':[21,22,23]})

df.head()

a   b
0  11  21
1  25  22
2  31  23

In [97]:
df.iloc[0,1]

21

In [102]:
import pandas as pd
df=pd.DataFrame({'a':[1,2,1],'b':[1,1,1]})

df['a']==1

0     True
1    False
2     True
Name: a, dtype: bool

In [107]:
import numpy as np
np.array([1,1])*np.array([1,1])

array([1, 1])

In [117]:
np.dot(np.array([1,1]),np.array([1,1]))

2

In [116]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [119]:
a=np.array([0,1]),b=np.array([1,0])

np.dot(a,b)

SyntaxError: cannot assign to function call (3771160541.py, line 1)

In [120]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])